//Name:Nancy Gomez
//Name:Regie Daquioag
//Name:Thalia Villalobos
//16 Oct. 2015
//

#include<iostream>
#include<string>
#include<cassert>
using namespace std;

char menu();
//***************************************************
//Precondition: When we first start this function inside int main() it will call this function and it will print out the options this program will have, The options are (+,-,*,/,Q).  
//Postcondition: It will return the char choice the user picked and that will go inside the int main() and it will be used in a switch to actually pick which section they wanted.
//Summary: It asks the user what section they would like to work in.
//***************************************************

int randGen();
//***************************************************
//Precondition: Takes in no parameters, is called in every single math function twice
//Postcondition: A random number is generated with numbers between 1 to 12. Returns that number to wherever it was called.
//Summary: Creates a random number between 1 through 12
//***************************************************

int addition();
//***************************************************
//Precondition: It takes in no parameter and t will be called upon depending on what char the user choices for this function it will be ‘+’.
//Postcondition: Inside of a for loop, two random numbers are generated by calling the randGen() functions for every question. A variable called count will keep track of how many questions were answered correctly. A Either compliment()  or encourage() will be called depending on whether the question was answered correct or not. Finally, count will be returned to main().
//Summary: The function will generate divisible division questions, ensure the numbers are reasonable, keep track of the correctly answered questions, and return that number to main().
//***************************************************

int subtraction();
//***************************************************
//Precondition: It takes in no parameter and t will be called upon depending on what char the user choices for this function it will be ‘-’.
//Postcondition: Inside of a for loop, two random numbers are generated by calling the randGen() functions for every question. A variable called count will keep track of how many questions were answered correctly. A Either compliment()  or encourage() will be called depending on whether the question was answered correct or not. Finally, count will be returned to main().
//Summary: The function will generate divisible division questions, ensure the numbers are reasonable, keep track of the correctly answered questions, and return that number to main().
//***************************************************

int multiplication();
//***************************************************
//Precondition: Takes in no parameters, is called depending on the char on the char that was chosen. The char for this one should be ‘*’.
//Postcondition: Inside of a for loop, two random numbers are generated by calling the randGen() functions for every question. A variable called count will keep track of how many questions were answered correctly. Either compliment()  or encourage() will be called depending on whether the question was answered correct or not. Finally, count will be returned to main().
//Summary: The function will generate multiplication questions, keep track of the correctly answered questions, and return that number to main().
//***************************************************

int division();
//***************************************************
//Precondition: Takes in no parameters, is called depending on the char on the char that was chosen. The char for this one should be ‘/’.
//Postcondition: Inside of a for loop, two random numbers are generated by calling the randGen() functions for every question. A variable called count will keep track of how many questions were answered correctly. A while loop will ensure that the numbers are actually divisible and will not have division by zero. Either compliment()  or encourage() will be called depending on whether the question was answered correct or not. Finally, count will be returned to main().
//Summary: The function will generate divisible division questions, ensure the numbers are reasonable, keep track of the correctly answered questions, and return that number to main().
//***************************************************

string compliment();
//***************************************************
//Precondition: 
//Postcondition: 
//Summary: 
//***************************************************

string encouragement();
//***************************************************
//Precondition: 
//Postcondition: 
//Summary: 
//***************************************************


int main()
{



    return 0;
}
 
 
char menu()
{



}
 
int randGen()
{


}
 
int addition()
{



}
 
int subtraction()
{


}

int multiplication()
{


}

int division()
{

}

string compliment()
{



}

string encouragement()
{



}


